shared: &shared
  registration:
    private: true
    beta: true
    open: true
  signup:
    prompt: false
  activation:
    prompt: false
  admin:
    name: "Administrator"
    email: "admin@example.com"
  notifier:
    host: "localhost:3000"
    name: "User Notifier"
    email: "noreply@example.com"

development:
  <<: *shared

test:
  <<: *shared

staging:
  <<: *shared

production:
  <<: *shared
